development:
  host: illiniregnow.com
  port: 27017
  database: courses

environment: development
netid: NETID
password: PASSWORD
twilio_account_sid: TWILIO_ACCOUNT_SID
twilio_auth_token: TWILIO_AUTH_TOKEN
